package net.littlelite.jurpe.system.resources;

/**
 J.U.R.P.E. @version@
 Copyright (C) 2002-12 LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

/**
 * Jurpe Library Strings
 * 
 * @author Robot
 */
public class English_Strings extends java.util.ListResourceBundle
{

	private static final Object[][] contents = new String[][]
	{
	{ "String_1", "Blocking with ready shield" },
	{ "String_2", "Dodging" },
	{ "String_3", "Parrying with ready weapon" },
	{ "String_1b", "Blocking with ready shield (based on Shield skill)" },
	{ "String_2b", "Dodging (based on current DX)" },
	{ "String_3b", "Parrying with ready weapon (based on Weapon skill)" },
	{ "String_4", " against that!" },
	{ "String_5", " cannot attack two times with an unbalanced weapon!" },
	{ "String_6", "makes an All Out Attack (" },
	{ "String_7", "Two Attacks" },
	{ "String_8", "+4 bonus skill" },
	{ "String_9", "+2 damage" },
	{ "String_10", "All Out Attack bonus to damage: " },
	{ "String_11", "Amulet" },
	{ "String_12", " and begins to fight." },
	{ "String_13", " and follows." },
	{ "String_14", "... and makes " },
	{ "String_15", " and receives " },
	{ "String_16", "Armor" },
	{ "String_17", "attack modifier (" },
	{ "String_18", " attacks " },
	{ "String_19", "\'s attack fails " },
	{ "String_20", "\'s attack is valid " },
	{ "String_21", "Balanced" },
	{ "String_22", "Based upon:" },
	{ "String_23", "Belt" },
	{ "String_24", "Bestiary Loaded" },
	{ "String_25", " blocks with shield." },
	{ "String_26", " cannot escape!!" },
	{ "String_27", " can\'t make an all out defense: only one active defense is available!" },
	{ "String_28", " can\'t be used." },
	{ "String_29", " can\'t defend " },
	{ "String_30", "Creating random items." },
	{ "String_31", "Critical Success (" },
	{ "String_32", "Critical Failure (" },
	{ "String_33", "aim" },
	{ "String_34", "all out attack" },
	{ "String_35", "all out defense" },
	{ "String_36", "attack" },
	{ "String_37", "move" },
	{ "String_38", "ready weapon" },
	{ "String_39", "reload" },
	{ "String_40", "Combat" },
	{ "String_41", "HT" },
	{ "String_42", "Value" },
	{ "String_43", "It\'s a CRITICAL HIT!" },
	{ "String_44", "Crushing" },
	{ "String_45", "Current player is AI." },
	{ "String_46", "Current player is human" },
	{ "String_47", "Current path is > " },
	{ "String_48", "Cutting" },
	{ "String_49", " damages." },
	{ "String_50", " active defense points." },
	{ "String_51", " an All Out Defense chance." },
	{ "String_52", " defends well." },
	{ "String_53", " defenses are " },
	{ "String_54", " passive defense points." },
	{ "String_55", "DX" },
	{ "String_56", " dodges." },
	{ "String_57", "$ per hour" },
	{ "String_58", "dexterity modifier (" },
	{ "String_59", "Easy" },
	{ "String_60", " escapes!!" },
	{ "String_61", "experience points" },
	{ "String_62", " falls unconscious." },
	{ "String_63", " is faster than " },
	{ "String_64", "Female" },
	{ "String_65", "First Aid unsuccesful: you roll " },
	{ "String_66", "ST" },
	{ "String_67", "First Aid successful: you roll " },
	{ "String_68", "First Aid unsuccesful: you roll " },
	{ "String_69", "Hard" },
	{ "String_70", " has " },
	{ "String_71", " has RD of " },
	{ "String_72", " has SPEED of " },
	{ "String_73", "health modifier (" },
	{ "String_74", " HT points" },
	{ "String_75", "High Scores" },
	{ "String_76", "HP" },
	{ "String_77", " HT points" },
	{ "String_78", "Items created and shuffled." },
	{ "String_79", "Impaling" },
	{ "String_80", " inflicts " },
	{ "String_81", "IQ" },
	{ "String_82", " is " },
	{ "String_83", " is NOT ready to combat." },
	{ "String_84", " is ready to attack." },
	{ "String_85", " is ready to combat." },
	{ "String_86", " is unconscious." },
	{ "String_87", "Item" },
	{ "String_88", "intelligence modifier (" },
	{ "String_89", "Lace" },
	{ "String_90", "loaded." },
	{ "String_91", " prepares an All Out Defense" },
	{ "String_92", " executes an All Out Attack!" },
	{ "String_93", "Male" },
	{ "String_94", "Max Damage: " },
	{ "String_95", "Dictionary loaded." },
	{ "String_96", "Medium" },
	{ "String_97", "Mental" },
	{ "String_98", "Min Strength: " },
	{ "String_99", "\'s miserably misses (automatic miss)" },
	{ "String_100", "Modify " },
	{ "String_101", "Money" },
	{ "String_102", " must defend." },
	{ "String_103", "MVMT" },
	{ "String_104", " MVMT is " },
	{ "String_105", "New combat: " },
	{ "String_106", "No damage is inflicted." },
	{ "String_107", "nothing" },
	{ "String_108", "Now AI chooses the next move..." },
	{ "String_109", " has no weapon to ready." },
	{ "String_110", "of Dexterity" },
	{ "String_111", "of Intelligence" },
	{ "String_112", "of Strength" },
	{ "String_113", "of the Sun" },
	{ "String_114", "of Wealth" },
	{ "String_115", "of Restore Health" },
	{ "String_116", " parries with ready weapon." },
	{ "String_117", " parries in a superb way." },
	{ "String_118", "Acute Sense" },
	{ "String_119", "Common Sense" },
	{ "String_120", "Danger Sense" },
	{ "String_121", "Daredevil" },
	{ "String_122", "Empathy" },
	{ "String_123", "Literacy" },
	{ "String_124", "Luck" },
	{ "String_125", "Night Vision" },
	{ "String_126", "Single-minded" },
	{ "String_127", "Strong Will" },
	{ "String_128", "Toughness" },
	{ "String_129", "Rapid healing" },
	{ "String_130", "Language Talent" },
	{ "String_131", "None" },
	{ "String_132", "Bad Sight" },
	{ "String_133", "Bully" },
	{ "String_134", "Cowardice" },
	{ "String_135", "Gluttony" },
	{ "String_136", "Greed" },
	{ "String_137", "Hard of Hearing" },
	{ "String_138", "Honesty" },
	{ "String_139", "Impulsiveness" },
	{ "String_140", "Jealousy" },
	{ "String_141", "Lame" },
	{ "String_142", "Laziness" },
	{ "String_143", "Miserliness" },
	{ "String_144", "One Eye" },
	{ "String_145", "None" },
	{ "String_146", "PD" },
	{ "String_147", "Phial" },
	{ "String_148", "Physical" },
	{ "String_149", "Potion" },
	{ "String_150", "RD" },
	{ "String_151", "Ready" },
	{ "String_152", " receives " },
	{ "String_153", "Requested Strength :" },
	{ "String_154", "Ring" },
	{ "String_155", "Life dice roll is " },
	{ "String_156", " rolls: " },
	{ "String_157", " rolls for damage..." },
	{ "String_158", "Running in " },
	{ "String_159", "): you completely restore your HT" },
	{ "String_160", "score points" },
	{ "String_161", "select your move." },
	{ "String_162", "Shield" },
	{ "String_163", "Shock reduces character IQ and DX of " },
	{ "String_164", "Shop Loaded." },
	{ "String_165", "Mad Mourn Store" },
	{ "String_166", "Swg" },
	{ "String_167", "Thr" },
	{ "String_168", "Skill" },
	{ "String_169", "Skills Loaded" },
	{ "String_170", "\'s skill with " },
	{ "String_171", "SPD" },
	{ "String_172", " points" },
	{ "String_173", "strength modifier (" },
	{ "String_174", "stat of " },
	{ "String_175", "It\'s a SUPER CRITICAL HIT!" },
	{ "String_176", "Damage after having applied weapon modifiers and passive defenses: " },
	{ "String_177", " that increases" },
	{ "String_178", " that restores " },
	{ "String_179", "): you lose 2 HT point" },
	{ "String_180", "Today a room at the inn costs " },
	{ "String_181", " tries to escape." },
	{ "String_182", "Turn" },
	{ "String_183", "Tutorial" },
	{ "String_184", "\'s unarmed combat skill is " },
	{ "String_185", "Unbalanced" },
	{ "String_186", "Unknown" },
	{ "String_187", " recovers!" },
	{ "String_188", " is in danger of collapse. Must roll for life." },
	{ "String_189", "Weapon" },
	{ "String_190", "Weight" },
	{ "String_191", " rolls for First Aid. " },
	{ "String_192", "You enter the High Score table!!" },
	{ "String_193", "You failed to enter High Score table" },
	{ "String_194", "You died." },
	{ "String_195", "You earned" },
	{ "String_196", "You find " },
	{ "String_197", "You loot the dead body of the monster." },
	{ "String_198", "You are NOT ready to attack. Ready your weapon first!" },
	{ "String_199", "You scored: " },
	{ "String_200", "You gain " },
	{ "String_201", " has attack modifier of " },
	{ "String_202", " is unconscious and cannot make any attack." },
	{ "String_203", "Your character has not been saved. Do you want to do it now?" },
	{ "String_204", "Game" },
	{ "String_205", "There's a threatening " },
	{ "String_206", "Nowhere to go from here..." },
	{ "String_207", "Ok" },
	{ "String_208", "You try to arrange a first aid." },
	{ "String_209", " has now " },
	{ "String_210", "Are you sure you want to exit?\nQuitting now will lose your progress in the game." },
	{ "String_211", "In the game it's " }

	};

	public Object[][] getContents()
	{
		return contents;
	}
}