/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) 2002-12 LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */
package net.littlelite.jurpedemo.frames.panels;

import java.awt.Color;
import javax.swing.ImageIcon;
import net.littlelite.jurpe.characters.PCharacter;
import net.littlelite.jurpedemo.JurpeDemoConfig;
import net.littlelite.jurpedemo.frames.JurpeMain;
import net.littlelite.jurpedemo.frames.TabbedPanel;
import net.littlelite.jurpedemo.resources.GameStrings;

/**
 * Inn tab panel
 */
public final class JPnlInn extends JPanelTemplate
{
	// UID
	private static final long serialVersionUID = 2L;

	/** Creates new form JPnlInn */
	public JPnlInn(JurpeMain gui)
	{
		super(gui);
		initComponents();
		this.setPanelDimension();
		this.setInnImage();
	}

	/**
	 * Refresh
	 */
	@Override
	public void refresh()
	{

		// Override "restorePanels()" policy when panel is shown
		if (this.isVisible())
		{
			this.parentGUI.enablePanel(TabbedPanel.TAB_INN, true);
		}

		PCharacter character = theSystem.getPC();
		int hourFee = theSystem.getInn().getCostPerHour();
		int nightFee = theSystem.getInn().getCostPerNight();
		this.jTxtInnFee.setText(String.valueOf(hourFee) + " $/h");
		this.jTxtOneNightFee.setText("$" + String.valueOf(nightFee));

		if (character != null && this.theSystem.isPCgenerated())
		{
			this.jTxtInnMoney.setText("$" + String.valueOf(character.getInventory().getAvailableMoney()));

			int currentHT = character.getPrimaryStats().getCurrentHitPoints();
			int currentFatigue = character.getPrimaryStats().getFatigue();
			int maxHT = character.getPrimaryStats().getHT();
			int firstAidLevel = 0;

			this.jLblInnName.setText(character.getName());
			this.jTxtInnHP.setText(String.valueOf(currentHT));
			this.jTxtInnHT.setText(String.valueOf(maxHT));

			// Set status related controls
			this.setStatus(character.isUnconscious(), currentHT, maxHT, currentFatigue);

			// First Aid Skill
			firstAidLevel = character.getSkillLevel("First Aid");
			this.jTxtInnFirstAid.setText(String.valueOf(firstAidLevel));
		}
		else
		{
			this.jTxtInnMoney.setText("");
			this.jLblInnName.setText("");
			this.jTxtInnHP.setText("0");
			this.jTxtInnHT.setText("00");
			this.jTxtInnStatus.setBackground(Color.white);
			this.jTxtInnStatus.setText("");
			this.jTxtInnFirstAid.setText("");
		}

	}

	private void setInnImage()
	{
		try
		{
			ImageIcon inn = this.rf.getResourceAsImage(JurpeDemoConfig.INNIMAGE);
			jLblInnImage.setIcon(inn);
		}
		catch (Exception exc)
		{
			exc.printStackTrace();
		}
	}

	private void setStatus(boolean unconscious, int currentHT, int maxHT, int currentFatigue)
	{

		// Status: Good / Hurt / Unconscious
		if (unconscious)
		{
			this.jBtnFirstAid.setEnabled(true);
			this.jTxtInnStatus.setBackground(Color.red);
			this.jTxtInnStatus.setText(GameStrings.UNCONSCI);
		}
		else if (currentHT < (maxHT / 2))
		{
			this.jBtnFirstAid.setEnabled(true);
			this.jTxtInnStatus.setBackground(Color.yellow);
			this.jTxtInnStatus.setText(GameStrings.HURTWXXX);
		}
		else if (currentHT == maxHT)
		{
			this.jBtnFirstAid.setEnabled(false);
			if (currentFatigue <= 0)
			{
				this.jTxtInnStatus.setBackground(Color.green);
				this.jTxtInnStatus.setText(GameStrings.OPTIMALJ);
			}
			else
			{
				this.jTxtInnStatus.setBackground(Color.yellow);
				this.jTxtInnStatus.setText("Fatigued");
			}
		}
		else
		{
			this.jBtnFirstAid.setEnabled(false);
			this.jTxtInnStatus.setBackground(Color.green);
			this.jTxtInnStatus.setText(GameStrings.GOODNNNN);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		jPnlCharSummary = new javax.swing.JPanel();
		jTxtInnHP = new javax.swing.JTextField();
		jTxtInnHT = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLblInnName = new javax.swing.JLabel();
		jTxtInnStatus = new javax.swing.JTextField();
		jTxtInnFirstAid = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTxtInnMoney = new javax.swing.JTextField();
		jPnlInnImage = new javax.swing.JPanel();
		jLblInnImage = new javax.swing.JLabel();
		btnRestOneNight = new javax.swing.JButton();
		jBtnRestOne = new javax.swing.JButton();
		btnExit = new javax.swing.JButton();
		jBtnFirstAid = new javax.swing.JButton();
		jTxtInnFee = new javax.swing.JTextField();
		jTxtOneNightFee = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		jPnlCharSummary.setBackground(new java.awt.Color(255, 255, 204));
		jPnlCharSummary.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jTxtInnHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTxtInnHP.setText("10");

		jTxtInnHT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTxtInnHT.setText("12");

		jLabel1.setLabelFor(jTxtInnHP);
		jLabel1.setText("Current HP");

		jLabel2.setLabelFor(jTxtInnHT);
		jLabel2.setText("Max HP");

		jLblInnName.setFont(jLblInnName.getFont().deriveFont(jLblInnName.getFont().getStyle() | java.awt.Font.BOLD));
		jLblInnName.setText("Hero");

		jTxtInnStatus.setBackground(new java.awt.Color(51, 255, 0));
		jTxtInnStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTxtInnStatus.setText("OK");

		jTxtInnFirstAid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTxtInnFirstAid.setText("12");

		jLabel4.setLabelFor(jTxtInnStatus);
		jLabel4.setText("Status");

		jLabel5.setLabelFor(jTxtInnFirstAid);
		jLabel5.setText("First Aid Skill");

		jLabel7.setText("Money");

		jTxtInnMoney.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTxtInnMoney.setText("$1000");

		javax.swing.GroupLayout jPnlCharSummaryLayout = new javax.swing.GroupLayout(jPnlCharSummary);
		jPnlCharSummary.setLayout(jPnlCharSummaryLayout);
		jPnlCharSummaryLayout.setHorizontalGroup(jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPnlCharSummaryLayout.createSequentialGroup()
						.addGroup(
								jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										jPnlCharSummaryLayout.createSequentialGroup().addContainerGap().addGroup(
												jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel1)
														.addComponent(jLabel2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
												jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(
														jTxtInnHT).addComponent(jTxtInnHP, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
										.addGroup(
												jPnlCharSummaryLayout.createSequentialGroup().addGroup(
														jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPnlCharSummaryLayout.createSequentialGroup().addContainerGap().addComponent(jLblInnName)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96,
																				Short.MAX_VALUE).addComponent(jLabel4)).addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPnlCharSummaryLayout.createSequentialGroup().addGap(105, 105, 105).addComponent(jLabel5))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		jPnlCharSummaryLayout.createSequentialGroup().addContainerGap(132, Short.MAX_VALUE)
																				.addComponent(jLabel7))).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
														jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																jTxtInnStatus, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE).addComponent(jTxtInnFirstAid,
																javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64,
																Short.MAX_VALUE).addComponent(jTxtInnMoney, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))).addContainerGap()));
		jPnlCharSummaryLayout.setVerticalGroup(jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPnlCharSummaryLayout.createSequentialGroup().addContainerGap().addGroup(
						jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLblInnName).addComponent(
								jTxtInnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel4)).addGap(25, 25, 25).addGroup(
						jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jTxtInnHP,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
								jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTxtInnHT,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2)).addGap(18, 18, 18).addGroup(
								jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTxtInnFirstAid,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
								jPnlCharSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTxtInnMoney,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel7)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPnlInnImage.setBackground(new java.awt.Color(255, 255, 204));
		jPnlInnImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPnlInnImage.setLayout(new java.awt.BorderLayout(5, 5));

		jLblInnImage.setBackground(new java.awt.Color(255, 255, 255));
		jLblInnImage.setMaximumSize(new java.awt.Dimension(216, 178));
		jLblInnImage.setMinimumSize(new java.awt.Dimension(216, 178));
		jLblInnImage.setPreferredSize(new java.awt.Dimension(216, 178));
		jPnlInnImage.add(jLblInnImage, java.awt.BorderLayout.CENTER);

		btnRestOneNight.setText("Rest One Night");
		btnRestOneNight.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnRestOneNightActionPerformed(evt);
			}
		});

		jBtnRestOne.setText("Rest One Hour");
		jBtnRestOne.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jBtnRestOneActionPerformed(evt);
			}
		});

		btnExit.setText("Exit");
		btnExit.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnExitActionPerformed(evt);
			}
		});

		jBtnFirstAid.setText("Use First Aid");
		jBtnFirstAid.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jBtnFirstAidActionPerformed(evt);
			}
		});

		jTxtInnFee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTxtInnFee.setText("0");

		jTxtOneNightFee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTxtOneNightFee.setText("0");

		jLabel3.setText("Inn hourly price");

		jLabel6.setText("Entire night fee");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								layout.createSequentialGroup().addComponent(jPnlCharSummary, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGap(22, 22, 22).addComponent(jPnlInnImage,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addComponent(btnExit,
								javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)).addGroup(
												layout.createSequentialGroup().addComponent(jLabel6).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED))).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(jTxtOneNightFee,
												javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTxtInnFee, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jBtnFirstAid,
												javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jBtnRestOne,
												javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(btnRestOneNight,
												javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPnlInnImage,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jPnlCharSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19,
						Short.MAX_VALUE).addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								layout.createSequentialGroup().addComponent(btnRestOneNight)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jBtnRestOne).addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jBtnFirstAid).addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE).addComponent(btnExit)).addGroup(
								layout.createSequentialGroup().addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(jTxtInnFee,
												javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(
														jTxtOneNightFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))).addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void jBtnFirstAidActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jBtnFirstAidActionPerformed
		parentGUI.useFirstAid();
	}// GEN-LAST:event_jBtnFirstAidActionPerformed

	private void btnRestOneNightActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnRestOneNightActionPerformed
		parentGUI.useRest();
	}// GEN-LAST:event_btnRestOneNightActionPerformed

	private void jBtnRestOneActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jBtnRestOneActionPerformed
		parentGUI.useNaturalRecovery();
	}// GEN-LAST:event_jBtnRestOneActionPerformed

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnExitActionPerformed
		parentGUI.showPanel(TabbedPanel.TAB_GAME);
		parentGUI.restorePanels();
	}// GEN-LAST:event_btnExitActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnExit;
	private javax.swing.JButton btnRestOneNight;
	private javax.swing.JButton jBtnFirstAid;
	private javax.swing.JButton jBtnRestOne;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLblInnImage;
	private javax.swing.JLabel jLblInnName;
	private javax.swing.JPanel jPnlCharSummary;
	private javax.swing.JPanel jPnlInnImage;
	private javax.swing.JTextField jTxtInnFee;
	private javax.swing.JTextField jTxtInnFirstAid;
	private javax.swing.JTextField jTxtInnHP;
	private javax.swing.JTextField jTxtInnHT;
	private javax.swing.JTextField jTxtInnMoney;
	private javax.swing.JTextField jTxtInnStatus;
	private javax.swing.JTextField jTxtOneNightFee;
	// End of variables declaration//GEN-END:variables
}
