/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */
package net.littlelite.jurpedemo.frames.panels;

import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import net.littlelite.jurpe.characters.PCharacter;
import net.littlelite.jurpedemo.frames.JurpeMain;
import net.littlelite.jurpedemo.frames.TabbedPanel;

/**
 * Base UI class for Shop template
 * 
 */
public class JPnlShop extends JPanelTemplate
{

	// UID
	private static final long serialVersionUID = 2L;

	protected JTree jTree = null;
	protected DefaultMutableTreeNode top = null;
        protected int pcMoney;

	/** Creates new form JPnlShop */
	public JPnlShop(JurpeMain gui)
	{
		super(gui);
		initComponents();
		this.setPanelDimension();
		this.initTree();
	}

	private void initTree()
	{
		jTree = new JTree();
		jTree.setShowsRootHandles(true);
	}

	/**
	 * Shop Refresh
	 * 
	 * @see net.littlelite.jurpedemo.frames.panels.TemplatePanel#refresh()
	 */
	@Override
	public void refresh()
	{
		// Override "restorePanels()" policy when panel is shown
		if (this.isVisible())
		{
			this.parentGUI.enablePanel(TabbedPanel.TAB_SHOP, true);
		}

		PCharacter curPC = theSystem.getPC();
		String denaro = " $";
		if (curPC != null)
		{
                    this.pcMoney = curPC.getInventory().getAvailableMoney();
                    this.txtShopMoney.setText(denaro + String.valueOf(this.pcMoney));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtShopMoney = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        jLabel1.setText("Shop available items");

        jLabel2.setText("Money:");

        txtShopMoney.setEditable(false);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtShopMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExit))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtShopMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        parentGUI.showPanel(TabbedPanel.TAB_GAME);
        parentGUI.restorePanels();
    }//GEN-LAST:event_btnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField txtShopMoney;
    // End of variables declaration//GEN-END:variables
}
