package net.littlelite.jurpedemo.resources;

/**
 J.U.R.P.E. @version@
 Copyright (C) 2002-12 LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

/**
 * JurpeDemo Strings
 * 
 * @author Robot
 */
public class English_Strings extends java.util.ListResourceBundle
{
	private static final Object[][] contents = new String[][]
	{
	{ "String_1", "About" },
	{ "String_2", "--- Active Defense ---" },
	{ "String_3", "Active Defense set to " },
	{ "String_4", "Active Defense" },
	{ "String_5", "AD" },
	{ "String_6", "Advantage" },
	{ "String_7", "All Out Attack" },
	{ "String_8", "Alone, with not enough money, you are left dying at the entrance." },
	{ "String_9", "You already learned " },
	{ "String_10", "Monsters in arena" },
	{ "String_11", "Arena" },
	{ "String_12", "You are not armed." },
	{ "String_13", "Armors" },
	{ "String_14", "Auto ready weapon" },
	{ "String_15", "Automatically ready unbalanced weapon" },
	{ "String_16", "Attack" },
	{ "String_17", "Available Money" },
	{ "String_18", "Available objects" },
	{ "String_19", "Available Skills" },
	{ "String_20", "After a short discussion, you obtain a price of " },
	{ "String_21", "Based on" },
	{ "String_22", "Blocking" },
	{ "String_23", "Buy" },
	{ "String_24", "You can\'t use First Aid while unconscious!" },
	{ "String_25", "You cannot learn " },
	{ "String_26", "Can\'t save." },
	{ "String_27", "You cannot wear " },
	{ "String_28", "Character" },
	{ "String_29", "Character created." },
	{ "String_30", "Current character is not armed." },
	{ "String_31", "--- Character Points ---" },
	{ "String_32", "Character Points" },
	{ "String_33", "): you lose 2 HT point" },
	{ "String_34", "Configuration file loaded." },
	{ "String_35", "A combat is still taking place... can\'t close now!" },
	{ "String_36", "Combat is over." },
	{ "String_37", "Command" },
	{ "String_38", "Constitution" },
	{ "String_39", "You must first create a character!" },
	{ "String_40", "): you completely restore your HT" },
	{ "String_41", "Critical Failure (" },
	{ "String_42", "Critical Success (" },
	{ "String_43", "Crushing: no bonus damage. Minimum Damage is 0." },
	{ "String_44", "Current" },
	{ "String_45", "Current weapon mode is: " },
	{ "String_46", "Current character is not armed" },
	{ "String_47", "Current Weapon" },
	{ "String_48", "Cutting: damage that gets through the armor is increased by 50%. Minimum Damage is 1." },
	{ "String_49", "Damage" },
	{ "String_50", "Damage Resistance" },
	{ "String_51", "30 minutes" },
	{ "String_52", "Delete existing character?" },
	{ "String_53", "Dexterity" },
	{ "String_54", "Difficulty" },
	{ "String_55", "Disadvantage" },
	{ "String_56", "Do you want to learn \'" },
	{ "String_57", "Dodging" },
	{ "String_58", "Do you want to drop " },
	{ "String_59", "Do you want to spend the night (8 hours) at the Inn?" },
	{ "String_60", "Drop" },
	{ "String_61", "Do you want to unwear " },
	{ "String_62", "Do you want to use " },
	{ "String_63", ". Do you accept?" },
	{ "String_64", "Encumbrance" },
	{ "String_65", "Examine" },
	{ "String_66", "Exit" },
	{ "String_67", "You FAILED to recover: roll " },
	{ "String_68", "Fight" },
	{ "String_69", "File" },
	{ "String_70", "First Aid" },
	{ "String_71", "First Aid successful: you roll " },
	{ "String_72", "Force" },
	{ "String_73", " for " },
	{ "String_74", "You already have full health!" },
	{ "String_75", "Generate" },
	{ "String_76", "Generate New" },
	{ "String_77", "Go" },
	{ "String_78", "Good" },
	{ "String_79", "JURPE Site" },
	{ "String_80", " has MVMT of " },
	{ "String_81", "Help" },
	{ "String_82", " hours" },
	{ "String_83", "Hurt" },
	{ "String_84", "Impaling: damage that gets through the armor is doubled. Minimum Damage is 1." },
	{ "String_85", "Improve" },
	{ "String_86", "Improving skill level for " },
	{ "String_87", "Input a Name for character" },
	{ "String_88", "Intelligence" },
	{ "String_89", "Inventory" },
	{ "String_90", "is ended." },
	{ "String_91", " is not usable." },
	{ "String_92", " is not wearable." },
	{ "String_93", "Items" },
	{ "String_94", "It\'s the same as your Move score" },
	{ "String_95", "Level" },
	{ "String_96", "Levels" },
	{ "String_97", "Restore Character" },
	{ "String_98", "Load Character File" },
	{ "String_99", "Mental Skills" },
	{ "String_100", "Monster Weapon" },
	{ "String_101", "MOV" },
	{ "String_102", "You must first create a character!" },
	{ "String_103", "Name" },
	{ "String_104", "New Wave" },
	{ "String_105", "Next:" },
	{ "String_106", "No" },
	{ "String_107", "You don\'t have enough money" },
	{ "String_108", "You have no more skill points to spend" },
	{ "String_109", "You have no more character points to spend" },
	{ "String_110", "A character has not been generated yet." },
	{ "String_111", "Not yet implemented." },
	{ "String_112", "Objects" },
	{ "String_113", "Objects you can sell." },
	{ "String_114", "Objects in the shop." },
	{ "String_115", "OK" },
	{ "String_116", "Open..." },
	{ "String_117", "Optimal" },
	{ "String_118", "Other" },
	{ "String_119", " out of " },
	{ "String_120", "Overall" },
	{ "String_121", "Panels" },
	{ "String_122", " (parrying with an unbalanced weapon)" },
	{ "String_123", "Parrying" },
	{ "String_124", "--- Passive Defense ---" },
	{ "String_125", "Physical Skills" },
	{ "String_126", "Points" },
	{ "String_127", "Price Per Hour" },
	{ "String_128", "Passive Defense" },
	{ "String_129", "You recover: roll " },
	{ "String_130", "Remaining Points" },
	{ "String_131", "Restore" },
	{ "String_132", " rolls for First Aid. " },
	{ "String_133", "Run" },
	{ "String_134", "Save" },
	{ "String_135", "Save As..." },
	{ "String_136", "Save Character" },
	{ "String_137", "Save Character File" },
	{ "String_138", "Game Saved" },
	{ "String_139", "Score" },
	{ "String_140", "You selected All Out Attack type: " },
	{ "String_141", "You selected sex:" },
	{ "String_142", "Sell" },
	{ "String_143", "Selected Weapon:" },
	{ "String_144", "Sex" },
	{ "String_145", "Shields" },
	{ "String_146", "Shop" },
	{ "String_147", " skill points" },
	{ "String_148", "Skills" },
	{ "String_149", " HT points" },
	{ "String_150", "Status" },
	{ "String_151", "Swing" },
	{ "String_152", "Cannot load character: file not found" },
	{ "String_153", "Game Loaded" },
	{ "String_154", "System" },
	{ "String_155", "They offer " },
	{ "String_156", "Thrust" },
	{ "String_157", "Time to Spend in Inn" },
	{ "String_158", "You block with your shield. It\'s half of your shield skill" },
	{ "String_159", "Type" },
	{ "String_160", "You parry with your ready weapon. It\'s half of your skill with that weapon" },
	{ "String_161", "Tools" },
	{ "String_162", "Total Fee" },
	{ "String_163", "Tot. Attack" },
	{ "String_164", "Try to recover from unconsciousness in " },
	{ "String_165", "You try to recover from unconsciousness." },
	{ "String_166", " cannot enter in combat while unconscious." },
	{ "String_167", "You enter in combat with " },
	{ "String_168", "You gain " },
	{ "String_169", "Unconscious" },
	{ "String_170", "Use First Aid for " },
	{ "String_171", "Unwear" },
	{ "String_172", "You recover from unconsciousness!" },
	{ "String_173", "Use" },
	{ "String_174", "used." },
	{ "String_175", "SPD" },
	{ "String_176", "Do you want to buy " },
	{ "String_177", "Do you want to sell " },
	{ "String_178", "Wave:" },
	{ "String_179", "Weapons" },
	{ "String_180", "Equip" },
	{ "String_181", " will make an All Out Defense when attacked next turn." },
	{ "String_182", "with" },
	{ "String_183", "Would you like to spend " },
	{ "String_184", "Weapon Mode" },
	{ "String_185", "Yes" },
	{ "String_186", "You attack " },
	{ "String_187", "You bought a " },
	{ "String_188", "You are ready to attack." },
	{ "String_189", "You sold " },
	{ "String_190", "Are you sure?" },
	{ "String_191", "You wear " },
	{ "String_192", "you already wear a weapon!" },
	{ "String_193", "You failed to recover health." },
	{ "String_194", "You peacefully rest at the Inn." },
	{ "String_195", "You recover naturally 1 HT" },
	{ "String_196", " at zero cost" },
	{ "String_197", "Right click to interact" },
	{ "String_198", "Do you want to rest at the Inn for one hour?" },
	{ "String_199", "You recover one point of fatigue." },
	{ "String_200", "Inn" },
	{ "String_201", "You are carrying nothing." },
        { "String_202", " - You cannot use this!" },
        { "String_203", " - You cannot afford this!" },
        { "String_204", "Mages Guild" },
        { "String_205", "You exceeded maximum character points." },
        { "String_206", "You leave the Mages Guild." },
        { "String_207", "Farewell, then." },
        { "String_208", "Grimoire" }

	};

        @Override
	public Object[][] getContents()
	{
		return contents;
	}
}