/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */
package net.littlelite.jurpedemo.wizards;

import javax.swing.JOptionPane;
import net.littlelite.jurpe.characters.CharacterAttributes;
import net.littlelite.jurpe.system.Config;
import net.littlelite.jurpedemo.resources.GameStrings;

/**
 * Base panel class for any panel in the wizard dialog
 * 
 */
public abstract class AbstractWizardPanel extends javax.swing.JPanel
{
	private static final long serialVersionUID = 3317L;
	
    protected WizardController wizard;

    /** Creates new form AbstractWizardPanel */
    public AbstractWizardPanel(WizardController cc)
    {
        this.wizard = cc;
    }
    
    public AbstractWizardPanel()
    {
        this.wizard = null;
    }
    
    // This method is called when user presses "Next"
    // that is when the panel is to be dismissed
    public void updateCharacter()
    {
        return;
    }
    
    // This method is called when the panel is shown
    public void syncCharacter()
    {
        return;
    }
    
    protected String getCharacterPoints()
    {
        CharacterAttributes ca = this.wizard.getCharacterAttrs();
        return this.getCharacterPoints(ca.getCharacterPoints());
    }
    
    protected String getCharacterPoints(int characterPoints)
    {
        StringBuilder cPoints = new StringBuilder();
        cPoints.append(characterPoints);
        cPoints.append("/");
        cPoints.append(Config.AVAILABLE_POINTS);
        return cPoints.toString();
    }
    
    protected void showCharPointsLimitExceed()
    {
        JOptionPane.showMessageDialog(this, GameStrings.CPLIMIT, "Character Points Limit", JOptionPane.WARNING_MESSAGE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("unused")
	private void initComponents() {

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        System.out.println(this.getName()+" shown");
    }//GEN-LAST:event_formFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
