/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) 2002-12 LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */
package net.littlelite.jurpedemo.wizards;

import net.littlelite.jurpe.system.resources.ResourceFinder;

/**
 * The base class for the wizard dialog
 * 
 */
public class JWizard extends javax.swing.JDialog
{

    private static final long serialVersionUID = 3317L;
    
    private WizardController creation;
    private AbstractWizardPanel currentWizardPanel;

    /** Creates new form JWizardBase */
    public JWizard(java.awt.Frame parent, WizardController cc)
    {
        super(parent, true);
        this.creation = cc;
        initComponents();
        
        // Set initial panel
        this.currentWizardPanel = new PanelWizard0();
        this.pnlWizard.add(this.currentWizardPanel);
        this.setTitle(this.currentWizardPanel.getName());
        this.btnPrevious.setEnabled(false);
        
        // Set position
        this.setLocationRelativeTo(parent);
        
        // Set icon
        ResourceFinder rf = ResourceFinder.resources();
        lblWizardImg.setIcon(rf.getResourceAsImage("charwizardbak.gif"));
    }
    
    private void showNext()
    {
        this.showPanel(this.creation.getNext());
    }
    
    private void showPrevious()
    {
        this.showPanel(this.creation.getPrevious());
    }
    
    private void showPanel(AbstractWizardPanel nextWizardPanel)
    {
        // Updates character with the data in the current panel
        this.currentWizardPanel.updateCharacter();
        // Before showing the panel, synch next panel controls with character's data
        nextWizardPanel.syncCharacter();
        this.setWizardPanel(nextWizardPanel);
    }
    
    private void setWizardPanel(AbstractWizardPanel panel)
    {
        // Enable next-previous buttons
        if (this.creation.isFirstWizardPanel())
        {
            this.btnNext.setText("> Next");
            this.btnPrevious.setEnabled(false);
        }
        else if (this.creation.isLastWizardPanel())
        {
            this.btnNext.setText("Finish");
        }
        else
        {
            this.btnNext.setText("> Next");
            this.btnCancel.setEnabled(true);
            this.btnPrevious.setEnabled(true);
        }
        
        this.pnlWizard.remove(this.currentWizardPanel);
        this.pack();
        this.currentWizardPanel = panel;
        this.currentWizardPanel.setSize(this.pnlWizard.getSize());
        this.pnlWizard.add(this.currentWizardPanel);
        this.setTitle(this.currentWizardPanel.getName());
        this.pack();
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWizardImg = new javax.swing.JPanel();
        lblWizardImg = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlWizard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("wizard"); // NOI18N
        setResizable(false);

        pnlWizardImg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblWizardImg.setFocusable(false);

        javax.swing.GroupLayout pnlWizardImgLayout = new javax.swing.GroupLayout(pnlWizardImg);
        pnlWizardImg.setLayout(pnlWizardImgLayout);
        pnlWizardImgLayout.setHorizontalGroup(
            pnlWizardImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWizardImg, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        pnlWizardImgLayout.setVerticalGroup(
            pnlWizardImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWizardImg, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        btnNext.setText("> Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setText("< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        pnlWizard.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlWizardImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlWizard, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNext, btnPrevious});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlWizardImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlWizard, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext)
                            .addComponent(btnCancel))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (this.creation.isLastWizardPanel())
        {
            this.currentWizardPanel.updateCharacter();
            this.creation.setCreated();
            this.dispose();
        }
        else
        {
            this.showNext();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        this.showPrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnCancel;
    protected javax.swing.JButton btnNext;
    protected javax.swing.JButton btnPrevious;
    private javax.swing.JLabel lblWizardImg;
    private javax.swing.JPanel pnlWizard;
    private javax.swing.JPanel pnlWizardImg;
    // End of variables declaration//GEN-END:variables
}
