/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

package net.littlelite.jurpedemo.wizards;

/**
 *
 * @author  zzasa88
 */
public final class PanelWizard0 extends AbstractWizardPanel
{
    
    private static final long serialVersionUID = 3317L;
    
    private static final String WELCOMETEXT = "Welcome to the J.U.R.P.E. Character Creation Wizard.\n\n" + 
              "The character you are creating is a fierce warrior, a barbarian of some sort. " + 
              "He will be living in a small village, where his father lead him to the way of weapons and army. \n\n" + 
              "A legend says there's a pit somewhere in the village, leading down to a strange dungeon. " + 
              "If the warrior decides to enter the pit, he will face waves of monsters, more and more cruel and powerful." + 
              "\n\nChoose carefully the next attributes of your warrior, since those attributes will " + 
              "determine his or her fate.\n\nYou may also select a number of inborn skills for your character: " + 
              "they represent special innate ability of the character." + "\n\nEnjoy.";
   

    /** Creates new form PanelWizard0 */
    public PanelWizard0()
    {
        initComponents();
        this.txtWelcome.setText(WELCOMETEXT);
        this.setName("Welcome to JurpeDemo Character Creator wizard");
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtWelcome = new javax.swing.JTextArea();

        txtWelcome.setColumns(20);
        txtWelcome.setEditable(false);
        txtWelcome.setFont(new java.awt.Font("Dialog", 0, 10));
        txtWelcome.setLineWrap(true);
        txtWelcome.setRows(5);
        txtWelcome.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtWelcome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtWelcome;
    // End of variables declaration//GEN-END:variables
}
