package net.littlelite.jurpe.combat;

/**
 J.U.R.P.E. @version@
 Copyright (C) 2002-12 LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

import net.littlelite.jurpe.system.ICommand;

/**
 * Utility class for Command Design Pattern. Provides a functor for
 * combat.move()
 * 
 * @see ICombat
 * @see DualCombat
 * 
 */
public class Move implements ICommand
{
	private ICombat combat;

	/**
	 * Functor for Move Command
	 * 
	 * @param xCombat
	 *            Combat class in which method AllOutAttack is defined
	 */
	public Move(ICombat xCombat)
	{
		combat = xCombat;
	}

	/**
	 * Execute this command
	 * 
	 * @return boolean depending on context
	 */
	public boolean execute()
	{
		return combat.move();
	}

	/**
	 * Get log generated by command
	 * 
	 * @return log generated by command
	 */
	public String getLog()
	{
		return combat.log();
	}
}