/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

package net.littlelite.jurpedemo.frames;

/**
 * A class to show a simple dialog
 * 
 */
public class JDialogBase extends javax.swing.JDialog
{
	private static final long serialVersionUID = 2L;

	private String message;

	public JDialogBase(java.awt.Frame parent, String message)
	{
		super(parent, true);
		this.setLocationRelativeTo(parent);
		initComponents();
		this.setMessage(message);
	}

	public JDialogBase(java.awt.Frame parent, String message, String dialogTitle)
	{
		super(parent, true);
		this.setLocationRelativeTo(parent);
		initComponents();
		this.setMessage(message);
		this.setTitle(dialogTitle);
	}

	/** Creates new form JFrameDialog */
	public JDialogBase(java.awt.Frame parent, boolean modal, String message)
	{
		super(parent, modal);
		this.setLocationRelativeTo(parent);
		initComponents();
		this.setMessage(message);
	}

	public void setMessage(String message)
	{
		this.message = message;
		this.jTextPane.setText(this.message);
	}

	public String getMessage()
	{
		return this.message;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		this.jBtnOk = new javax.swing.JButton();
		this.jPanel1 = new javax.swing.JPanel();
		this.jScrollPane = new javax.swing.JScrollPane();
		this.jTextPane = new javax.swing.JTextPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		this.jBtnOk.setText("OK");
		this.jBtnOk.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jBtnOkActionPerformed(evt);
			}
		});

		this.jPanel1.setBackground(new java.awt.Color(223, 235, 247));

		this.jTextPane.setBackground(new java.awt.Color(223, 234, 246));
		this.jTextPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		this.jTextPane.setEditable(false);
		this.jScrollPane.setViewportView(this.jTextPane);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(this.jPanel1);
		this.jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(this.jScrollPane,
				javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(this.jScrollPane,
				javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(this.jPanel1, javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(this.jBtnOk,
								javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(this.jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(this.jBtnOk).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	void jBtnOkActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jBtnOkActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}// GEN-LAST:event_jBtnOkActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jBtnOk;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane;
	private javax.swing.JTextPane jTextPane;
	// End of variables declaration//GEN-END:variables
}
