/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

package net.littlelite.jurpedemo.frames;

import java.awt.Font;
import java.awt.Rectangle;
import java.awt.SystemColor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import net.littlelite.jurpe.system.Config;
import net.littlelite.jurpe.system.resources.ResourceFinder;

/**
 * About dialog form
 * 
 */
public class JDialogAbout extends javax.swing.JDialog
{

	private static final long serialVersionUID = 2L;
	private ResourceFinder rf;

	/**
         * Constructor
         * @param caller Form caller handler
         */
	public JDialogAbout(JFrame caller)
	{
		initComponents();

		this.initialize();
		if (caller != null)
		{
			this.setLocationRelativeTo(caller);
		}

		// UI
		this.jLabelJurpe.setText(Config.APPNAME + " " + Config.VERSION);
		this.initLicense();
	}

	/**
	 * This method initializes this
	 * 
	 * @return void
	 */
	private void initialize()
	{
		// Image
		this.rf = ResourceFinder.resources();
		ImageIcon topbar = this.rf.getResourceAsImage("jurpe-topbar.jpg");
		this.jLabelPicture.setBounds(new Rectangle(64, 15, 348, 59));
		this.jLabelPicture.setIcon(topbar);
                
                StyledDocument doc = this.jTextAreaGPL.getStyledDocument();
                SimpleAttributeSet center = new SimpleAttributeSet();
                StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
                doc.setParagraphAttributes(0, doc.getLength(), center, false);

		// License text
		this.jTextAreaGPL.setFont(new Font("Courier", Font.PLAIN, 10));

		// this.setSize(483, 329);
		this.setBackground(SystemColor.control);
		this.setResizable(false);
		this.setTitle("Jurpe - About");
	}

	private void initLicense()
	{
                String license = JDialogAbout.GPLV2_LICENSE;

			this.jTextAreaGPL.setText(license);
			this.jTextAreaGPL.setCaretPosition(0);
			this.jTextAreaGPL.setEditable(false);

		
	}
        
        
        private static final String GPLV2_LICENSE =
                "Copyright (C) LittleLite Software \n" +
                "\n" +
                "This program is free software; you can redistribute it and/or\n" +
                "modify it under the terms of the GNU General Public License\n" +
                "as published by the Free Software Foundation; either version 2\n" +
                "of the License, or (at your option) any later version.\n" +
                "\n" +
                "This program is distributed in the hope that it will be useful,\n" +
                "but WITHOUT ANY WARRANTY; without even the implied warranty of\n" +
                "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" +
                "GNU General Public License for more details.\n" +
                "\n" +
                "You should have received a copy of the GNU General Public License\n" +
                "along with this program; if not, write to the Free Software\n" +
                "Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, \nMA  02110-1301, USA.";
        

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jLabelPicture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelJurpe = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaGPL = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelPicture.setBackground(new java.awt.Color(255, 204, 204));
        jLabelPicture.setForeground(new java.awt.Color(255, 204, 204));
        jLabelPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Java Universal Role Playing Engine");

        jLabelJurpe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelJurpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJurpe.setText("JURPE v.X.X.X");

        jScrollPane2.setName(""); // NOI18N

        jTextAreaGPL.setName("jTextAreaGPL"); // NOI18N
        jScrollPane2.setViewportView(jTextAreaGPL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJurpe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 193, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelJurpe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabelPicture.getAccessibleContext().setAccessibleName("jLabelPicture");

        pack();
    }// </editor-fold>//GEN-END:initComponents

	void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton1ActionPerformed
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelJurpe;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextAreaGPL;
    // End of variables declaration//GEN-END:variables
}
