/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

package net.littlelite.jurpedemo.frames;

import javax.swing.DefaultListModel;

/**
 * The base class for combat dialog
 */
public class JDialogCombatBase extends javax.swing.JDialog
{

	private static final long serialVersionUID = 2L;

	/** Creates new form JDialogCombatBase */
	public JDialogCombatBase(java.awt.Frame parent)
	{
		super(parent);

		this.setLocationRelativeTo(parent);
		this.setModal(true);

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		jPnlFighter = new javax.swing.JPanel();
		jImgPC = new javax.swing.JLabel();
		jLblFighterName = new javax.swing.JLabel();
		jTxtHTFighter = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jTxtFighterReady = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTxtArmaCorrente = new javax.swing.JTextField();
		jCboWeaponMode = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jCboActiveDefense = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jPnlFightee = new javax.swing.JPanel();
		jImgMonster = new javax.swing.JLabel();
		jLblFighteeName = new javax.swing.JLabel();
		jTxtHTFighteee = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTxtFighteeReady = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTxtMonsterWeapon = new javax.swing.JTextField();
		jTxtMonsterWpnMode = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTxtMonsterActiveDef = new javax.swing.JTextField();
		jScrollPane = new javax.swing.JScrollPane();
		jLstLog = new javax.swing.JList();
		jChkAutoReady = new javax.swing.JCheckBox();
		jToolBar = new javax.swing.JToolBar();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setName("combatBase"); // NOI18N
		setResizable(false);

		jPnlFighter.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

		jImgPC.setText("jImgPC");
		jImgPC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLblFighterName.setFont(new java.awt.Font("Dialog", 1, 11));
		jLblFighterName.setText("Fighter");

		jTxtHTFighter.setEditable(false);
		jTxtHTFighter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTxtHTFighter.setText("15");

		jLabel1.setLabelFor(jTxtHTFighter);
		jLabel1.setText("Health (HP)");

		jTxtFighterReady.setEditable(false);
		jTxtFighterReady.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

		jLabel3.setText("Ready");

		jTxtArmaCorrente.setEditable(false);
		jTxtArmaCorrente.setText("Current Weapon");

		jCboWeaponMode.setModel(new javax.swing.DefaultComboBoxModel(new String[]
		{ "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel5.setText("Weapon");

		jCboActiveDefense.setModel(new javax.swing.DefaultComboBoxModel(new String[]
		{ "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel7.setText("Active Defense");

		javax.swing.GroupLayout jPnlFighterLayout = new javax.swing.GroupLayout(jPnlFighter);
		jPnlFighter.setLayout(jPnlFighterLayout);
		jPnlFighterLayout.setHorizontalGroup(jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPnlFighterLayout.createSequentialGroup().addContainerGap().addGroup(
						jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPnlFighterLayout.createSequentialGroup().addGroup(
										jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLblFighterName)
												.addGroup(
														jPnlFighterLayout.createSequentialGroup().addGroup(
																jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																		jLabel1).addComponent(jLabel3)).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
																jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																		jTxtHTFighter, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTxtFighterReady,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE).addComponent(jImgPC,
												javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPnlFighterLayout.createSequentialGroup().addComponent(jLabel5).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE).addGroup(
										jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(jCboWeaponMode,
												0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jTxtArmaCorrente,
												javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPnlFighterLayout.createSequentialGroup().addComponent(jLabel7).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE).addComponent(jCboActiveDefense,
										javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));

		jPnlFighterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]
		{ jTxtFighterReady, jTxtHTFighter });

		jPnlFighterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]
		{ jCboWeaponMode, jTxtArmaCorrente });

		jPnlFighterLayout.setVerticalGroup(jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPnlFighterLayout.createSequentialGroup().addContainerGap().addGroup(
						jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
								jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTxtFighterReady,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3)).addGroup(
								jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jImgPC,
										javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(
										jPnlFighterLayout.createSequentialGroup().addComponent(jLblFighterName).addGap(32, 32, 32).addGroup(
												jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
														.addComponent(jTxtHTFighter, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))).addGroup(
						jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPnlFighterLayout.createSequentialGroup().addGap(18, 18, 18).addComponent(jTxtArmaCorrente,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jCboWeaponMode,
												javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(
								jPnlFighterLayout.createSequentialGroup().addGap(34, 34, 34).addComponent(jLabel5))).addGap(18, 18, 18).addGroup(
						jPnlFighterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jCboActiveDefense,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7)).addContainerGap()));

		jPnlFighterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]
		{ jTxtFighterReady, jTxtHTFighter });

		jPnlFightee.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

		jImgMonster.setText("jImgMonster");
		jImgMonster.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLblFighteeName.setFont(new java.awt.Font("Dialog", 1, 11));
		jLblFighteeName.setText("Fightee");

		jTxtHTFighteee.setEditable(false);
		jTxtHTFighteee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTxtHTFighteee.setText("15");

		jLabel2.setLabelFor(jTxtHTFighteee);
		jLabel2.setText("Health (HP)");

		jTxtFighteeReady.setEditable(false);
		jTxtFighteeReady.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

		jLabel4.setLabelFor(jTxtFighteeReady);
		jLabel4.setText("Ready");

		jTxtMonsterWeapon.setEditable(false);
		jTxtMonsterWeapon.setText("Monster Weapon");

		jTxtMonsterWpnMode.setEditable(false);

		jLabel6.setText("Weapon");

		jLabel8.setText("Active Defense");

		jTxtMonsterActiveDef.setEditable(false);

		javax.swing.GroupLayout jPnlFighteeLayout = new javax.swing.GroupLayout(jPnlFightee);
		jPnlFightee.setLayout(jPnlFighteeLayout);
		jPnlFighteeLayout.setHorizontalGroup(jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPnlFighteeLayout.createSequentialGroup().addContainerGap().addGroup(
						jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPnlFighteeLayout.createSequentialGroup().addGroup(
										jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLblFighteeName)
												.addGroup(
														jPnlFighteeLayout.createSequentialGroup().addGroup(
																jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																		jLabel2).addComponent(jLabel4)).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
																jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
																		jTxtFighteeReady, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTxtHTFighteee,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE).addComponent(jImgMonster,
												javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(
								jPnlFighteeLayout.createSequentialGroup().addGroup(
										jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel6).addComponent(
												jLabel8)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(
										jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												jPnlFighteeLayout.createSequentialGroup().addGap(42, 42, 42).addComponent(jTxtMonsterActiveDef,
														javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(
												jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(
														jTxtMonsterWpnMode).addComponent(jTxtMonsterWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
														javax.swing.GroupLayout.PREFERRED_SIZE))))).addContainerGap()));

		jPnlFighteeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]
		{ jTxtFighteeReady, jTxtHTFighteee });

		jPnlFighteeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]
		{ jTxtMonsterWeapon, jTxtMonsterWpnMode });

		jPnlFighteeLayout.setVerticalGroup(jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPnlFighteeLayout.createSequentialGroup().addGap(12, 12, 12).addGroup(
						jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(
								jPnlFighteeLayout.createSequentialGroup().addGroup(
										jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
												jPnlFighteeLayout.createSequentialGroup().addComponent(jLblFighteeName).addGap(51, 51, 51)).addGroup(
												jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTxtHTFighteee,
														javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2))).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(
										jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTxtFighteeReady,
												javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel4))).addComponent(jImgMonster,
								javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
						jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPnlFighteeLayout.createSequentialGroup().addGap(19, 19, 19).addComponent(jTxtMonsterWeapon,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTxtMonsterWpnMode,
												javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE).addGap(16, 16, 16).addGroup(
												jPnlFighteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
														jTxtMonsterActiveDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel8))).addGroup(
								jPnlFighteeLayout.createSequentialGroup().addGap(36, 36, 36).addComponent(jLabel6))).addContainerGap(11, Short.MAX_VALUE)));

		jPnlFighteeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]
		{ jTxtFighteeReady, jTxtHTFighteee });

		jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

		jLstLog.setModel(new DefaultListModel());
		jScrollPane.setViewportView(jLstLog);

		jChkAutoReady.setText("Auto Ready Weapon");
		jChkAutoReady.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jChkAutoReady.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

		jToolBar.setRollover(true);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jScrollPane,
								javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE).addGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								layout.createSequentialGroup().addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 333,
										javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52,
										Short.MAX_VALUE).addComponent(jChkAutoReady)).addGroup(
								layout.createSequentialGroup().addComponent(jPnlFighter, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPnlFightee, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPnlFighter, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jPnlFightee,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jToolBar,
										javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jChkAutoReady))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE,
								114, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(16, Short.MAX_VALUE)));

		layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]
		{ jPnlFightee, jPnlFighter });

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected javax.swing.JComboBox jCboActiveDefense;
	protected javax.swing.JComboBox jCboWeaponMode;
	protected javax.swing.JCheckBox jChkAutoReady;
	protected javax.swing.JLabel jImgMonster;
	protected javax.swing.JLabel jImgPC;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	protected javax.swing.JLabel jLblFighteeName;
	protected javax.swing.JLabel jLblFighterName;
	protected javax.swing.JList jLstLog;
	protected javax.swing.JPanel jPnlFightee;
	protected javax.swing.JPanel jPnlFighter;
	private javax.swing.JScrollPane jScrollPane;
	protected javax.swing.JToolBar jToolBar;
	protected javax.swing.JTextField jTxtArmaCorrente;
	protected javax.swing.JTextField jTxtFighteeReady;
	protected javax.swing.JTextField jTxtFighterReady;
	protected javax.swing.JTextField jTxtHTFighteee;
	protected javax.swing.JTextField jTxtHTFighter;
	protected javax.swing.JTextField jTxtMonsterActiveDef;
	protected javax.swing.JTextField jTxtMonsterWeapon;
	protected javax.swing.JTextField jTxtMonsterWpnMode;
	// End of variables declaration//GEN-END:variables
}
