/**
 J.U.R.P.E. @version@ Swing Demo
 Copyright (C) LittleLite Software

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

package net.littlelite.jurpedemo.frames;

import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import net.littlelite.jurpe.system.Core;

/**
 * 
 * @author Alessio Saltarin
 */
public class JDialogScores extends javax.swing.JDialog
{

	private static final long serialVersionUID = 2L;

	private static final String[] highScoresColumns =
	{ "Pos", "Name", "Date", "Score" };

	private Core theSystem;

	/** Creates new form JFrameScores */
	public JDialogScores(JurpeMain owner)
	{
		theSystem = owner.getSystem();
		initComponents();

		// Set UI
		this.jTblHighScores.setModel(new HighScoresTableModel());
		this.setSize(380, 270);
		if (owner != null)
		{
			this.setLocationRelativeTo((JFrame) owner);
		}
		this.setColumnsWidth();
	}

	private Object[][] getHighScores()
	{
		return theSystem.getHighScores().getHighScores();
	}

	private void setColumnsWidth()
	{
		// Set preferred column widths
		TableColumn column = null;
		int colNum = JDialogScores.highScoresColumns.length;
		for (short i = 0; i < colNum; i++)
		{
			column = this.jTblHighScores.getColumnModel().getColumn(i);
			if (i == 0)
			{
				column.setPreferredWidth(5);
				column.setWidth(5);
			}
			else if (i == 1)
			{
				column.setPreferredWidth(10);
				column.setWidth(10);
			}
			else if (i == 3)
			{
				column.setPreferredWidth(50);
				column.setWidth(50);
			}

		}
	}

	class HighScoresTableModel extends AbstractTableModel
	{

		private static final long serialVersionUID = 1L;
		private String[] columnNames = JDialogScores.highScoresColumns;
		private Object[][] data = getHighScores();

		public int getColumnCount()
		{
			return columnNames.length;
		}

		public int getRowCount()
		{
			return data.length;
		}

		@Override
		public String getColumnName(int col)
		{
			return columnNames[col].toString();
		}

		public Object getValueAt(int row, int col)
		{
			return data[row][col];
		}

		/*
		 * public Class getColumnClass(int c) { return getValueAt(0,
		 * c).getClass(); }
		 */
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		jScrollPane1 = new javax.swing.JScrollPane();
		jTblHighScores = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Jurpe Demo High Scores");
		setMinimumSize(new java.awt.Dimension(370, 250));
		addComponentListener(new java.awt.event.ComponentAdapter()
		{
			public void componentResized(java.awt.event.ComponentEvent evt)
			{
				formComponentResized(evt);
			}
		});

		jTblHighScores.setModel(new javax.swing.table.DefaultTableModel(new Object[][]
		{
		{ null, null, null, null },
		{ null, null, null, null },
		{ null, null, null, null },
		{ null, null, null, null } }, new String[]
		{ "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTblHighScores);

		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(218, Short.MAX_VALUE).addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
						javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE).addGap(18, 18, 18)
						.addComponent(jButton1).addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void formComponentResized(java.awt.event.ComponentEvent evt)
	{// GEN-FIRST:event_formComponentResized
		// TODO add your handling code here:
	}// GEN-LAST:event_formComponentResized

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTblHighScores;
	// End of variables declaration//GEN-END:variables
}
